package xyz.zerotower.blog.entity;

import java.io.Serializable;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * @author ZeroTower
 * @TableName tb_cover
 */
@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
@TableName("tb_cover")
public class Cover implements Serializable {
    /**
     * 自增id
     *
     * @mbg.generated Fri Apr 09 21:44:05 CST 2021
     */
    @TableId(type = IdType.AUTO)
    private Integer id;

    /**
     * 页面url
     *
     * @mbg.generated Fri Apr 09 21:44:05 CST 2021
     */
    private String url;

    /**
     * 封面图片路径
     *
     * @mbg.generated Fri Apr 09 21:44:05 CST 2021
     */
    private String coverUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_cover
     *
     * @mbg.generated Fri Apr 09 21:44:05 CST 2021
     */
    private static final long serialVersionUID = 1L;
}